# Generated by Django 2.0.2 on 2018-03-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearterm', models.BigIntegerField(blank=True, db_column='Yearterm', null=True)),
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
                ('crse', models.BigIntegerField(blank=True, db_column='Crse', null=True)),
                ('sec', models.TextField(blank=True, db_column='Sec', null=True)),
                ('onlinefcq', models.TextField(blank=True, db_column='OnlineFCQ', null=True)),
                ('bdcontinedcrse', models.FloatField(blank=True, db_column='BDContinEdCrse', null=True)),
                ('instructor', models.TextField(blank=True, db_column='Instructor', null=True)),
                ('formsrequested', models.BigIntegerField(blank=True, db_column='FormsRequested', null=True)),
                ('formsreturned', models.BigIntegerField(blank=True, db_column='FormsReturned', null=True)),
                ('courseoverallpctvalid', models.TextField(blank=True, db_column='CourseOverallPctValid', null=True)),
                ('courseoverall', models.FloatField(blank=True, db_column='CourseOverall', null=True)),
                ('courseoverall_sd', models.FloatField(blank=True, db_column='CourseOverall_SD', null=True)),
                ('instructoroverall', models.FloatField(blank=True, db_column='InstructorOverall', null=True)),
                ('instructoroverall_sd', models.FloatField(blank=True, db_column='InstructorOverall_SD', null=True)),
                ('hoursperwkinclclass', models.TextField(blank=True, db_column='HoursPerWkInclClass', null=True)),
                ('priorinterest', models.FloatField(blank=True, db_column='PriorInterest', null=True)),
                ('instreffective', models.FloatField(blank=True, db_column='InstrEffective', null=True)),
                ('availability', models.FloatField(blank=True, db_column='Availability', null=True)),
                ('challenge', models.FloatField(blank=True, db_column='Challenge', null=True)),
                ('howmuchlearned', models.FloatField(blank=True, db_column='HowMuchLearned', null=True)),
                ('instrrespect', models.FloatField(blank=True, db_column='InstrRespect', null=True)),
                ('crstitle', models.TextField(blank=True, db_column='CrsTitle', null=True)),
                ('r_presnt', models.FloatField(blank=True, db_column='R_Presnt', null=True)),
                ('r_fair', models.FloatField(blank=True, db_column='R_Fair', null=True)),
                ('workload', models.FloatField(blank=True, db_column='Workload', null=True)),
                ('r_divstu', models.FloatField(blank=True, db_column='R_Divstu', null=True)),
                ('r_access', models.FloatField(blank=True, db_column='R_Access', null=True)),
                ('r_learn', models.FloatField(blank=True, db_column='R_Learn', null=True)),
                ('campus', models.TextField(blank=True, db_column='Campus', null=True)),
                ('college', models.TextField(blank=True, db_column='College', null=True)),
                ('asdiv', models.TextField(blank=True, db_column='ASdiv', null=True)),
                ('level', models.TextField(blank=True, db_column='Level', null=True)),
                ('fcqdept', models.TextField(blank=True, db_column='Fcqdept', null=True)),
                ('instr_group', models.TextField(blank=True, db_column='Instr_Group', null=True)),
                ('i_num', models.BigIntegerField(blank=True, db_column='I_Num', null=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
